blank_issues_enabled: false
contact_links:
  - name: "Branch Support"
    url: https://help.branch.io/using-branch/page/submit-a-ticket
    about: If you are having general trouble with Branch SDK (not Flutter Plugin), please submit a ticket to Branch Support or open an issue in the platform repository:
    * iOS: [https://github.com/BranchMetrics/ios-branch-deep-linking-attribution](https://github.com/BranchMetrics/ios-branch-deep-linking-attribution)
    * Android: [https://github.com/BranchMetrics/android-branch-deep-linking-attribution](https://github.com/BranchMetrics/android-branch-deep-linking-attribution)
